### PR TITLE
move environment's out of version control

### PR DESCRIPTION
**Pull request by ZhoraKornev**
Yep - i hope you will develop this repo to production mode.
It's looking good you use releases and auto git scripts.
Nice work bro.

### CODE REVIEW

**Comment by alexyao2015** [comment]
Thanks. I don't believe these changes are really necessary. The .env file there is to serve as an example. The port mapping can be changed in the docker-compose file. There doesn't seem to be a clear purpose to mapping it to the env file.

**Comment by ZhoraKornev** [comment]
but not evryone have stand alone server so config ports and secrets out of version control must have

**Comment by alexyao2015** [comment]
Sure you can still configure the ports on your own copy of the .env file or docker-compose file. Those are just examples.

**Comment by ZhoraKornev** [comment]
the .env file under version control and on new pulls it can be overwriting! 
Bad bractice.

**Pull request closed without merging**
